name: Deploy

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: tcgone-deploy # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: REPO_USERNAME # env var name
        server-password: REPO_PASSWORD # env var name
    - name: Cache Maven
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Deploy Project
      run: mvn --batch-mode --update-snapshots deploy
      env:
        REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
        REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
